# YAML config file with default parameters for map2gazebo

# Topic that the map to convert is being published on
map2gazebo:
  ros__parameters:
    map_topic: "/map"
    # Can be "stl" or "dae"
    mesh_type: "dae"
    # Minimum threshold value for considering a map cell occupied
    occupied_thresh: 99
    # Height of boxes in gazebo environment
    box_height: 1.5

    export_dir: "/home/sarantin/Desktop"